dist/angular-google-maps.js

Fill was missing as parameter on uiGmapPolygons directive

Add 'fill' as parameter on Polygons

---

app/views/directive/marker-label.html

This is #1062 on correct branch.

Fix html error

---

app/views/directive/google-map.html
app/views/examples/google-map/index.html

removed unexisting property from docs #1096

---

app/views/directive/circle.html
app/views/examples/circle/index.html
app/views/examples/circle/script.js

Adds the documentation to the website for the new circle directive `control` parameter added in pull request #1150 and requested from issue #658

Add documentation for new circle directive `control` parameter

---

Gruntfile.coffee
app/index.html
app/scripts/app.js
app/scripts/controllers/api.js
app/scripts/directives/affix.js
app/views/directive/circle.html
app/views/directive/google-map.html
app/views/directive/marker.html
app/views/directive/markers.html
app/views/directive/partials/events.html
app/views/directive/partials/plural.html
app/views/directive/partials/polys.html
app/views/directive/polygon.html
app/views/directive/polygons.html
app/views/directive/polyline.html
app/views/directive/window.html
app/views/directive/windows.html
bower.json
grunt/options.coffee

control updates documented
polygons added and re-used polylines template
#1086

issue 1086 control doc updates for 2.0.13

---

app/views/service/IsReady.html

fixed issue #864

---

spec/coffee/providers/google-map-api-provider.spec.coffee
src/coffee/providers/map-loader.coffee

Fixes #767 
I'm not sure what could happen if the 'online' event is triggered twice though..
I'm open to any suggestion :)

load maps when device is online

---

src/coffee/providers/map-loader.coffee

Fix this issue:
https://github.com/angular-ui/angular-google-maps/issues/1186

Fix issue #1186

---

src/coffee/directives/api/utils/model-key.coffee

Allow nested properties for marker coords

---

src/coffee/directives/api/utils/is-ready.coffee

Simple fix for: https://github.com/angular-ui/angular-google-maps/issues/1289

fix proms length sometimes lower than 0

---

app/views/directive/markers.html

Please, check if its definition is ok.

Duplicate labelContent

---

app/scripts/controllers/footer.js
app/styles/main.css
app/views/footer.html

I figured I'd open a PR for this since nobody else from the community is willing to fix this issue https://github.com/angular-ui/angular-google-maps/issues/1378. I also added a "No results" fallback in case something goes wrong.

fixed latest commit section from footer

---

.editorconfig
app/scripts/controllers/api.js
app/views/provider/GoogleMapApi.html
bower.json

This fixes https://github.com/angular-ui/angular-google-maps/issues/1380
Due to one of my plugins from Sublime, which automatically formats .js files, the diff got pretty damn big. However, you should check out line 48 to see the actual modification I did.
Thanks!

added links to specific api documentation parts

---

app/scripts/controllers/footer.js
app/views/footer.html
app/views/use.html

1. Because the contributors list from the footer was pretty big, I modified it so now we're displaying the 20 most active ones while providing a link to the repo's [contributors](https://github.com/angular-ui/angular-google-maps/graphs/contributors) page for the rest of them
2. Contributors avatars now link to real GitHub profiles(previously were linked to api.github.com/users/username)
3. Swapped out the static "© 2013 - 2014" in favour of dynamic value for current year
4. Fixed https://github.com/angular-ui/angular-google-maps/issues/1206

Multiple footer improvements and fix for #1206

---

example/issue-147-ng-show-map-refresh.html

issue-147-ng-show-map-refresh.html

---

example/assets/scripts/controllers/issue-147-ng-show-map-refresh.js

issue 147 controller ( refresh hidden map)

issue-147-ng-show-map-refresh.js

---

app/views/directive/marker.html

I've fixed the html that's broken.

Documentation marker <td> fix

---

example/example.html

Fixed 'repear' to 'repeat' in example/example.html

[Cleanup] Typo in example/example.html

---

app/views/examples/base/base.html
app/views/examples/search-box/index.html
app/views/examples/search-box/script.js
grunt/options.coffee

Let's see if this gets the places library to load within the plunkr in the API docs. The code works in Plunkr by itself.

modified searchbox example

---

bower.json

Temporary fix to lodash 4.0 release.

revert to lodash 3.8.0 version

---

spec/coffee/directives/api/models/parent/markers-parent-model.spec.coffee
src/coffee/directives/api/map.coffee
src/coffee/directives/api/utils/events-helper.coffee
src/coffee/directives/api/utils/model-key.coffee
src/coffee/extensions/lodash.coffee

a number of aliases have been removed from the [next major version of lodash](https://github.com/lodash/lodash/tree/4.0.0/doc)

change aliases removed from lodash v4

---

app/index.html

waffle, not trello

---

src/coffee/extensions/lodash.coffee

Note: I had trouble compiling and creating the JS files at home on my machine but I think it compiled fine at work earlier (if you can compile and create the files from the coffeescript that would be great.)

lodash 4 compatibility

---

src/coffee/extensions/lodash.coffee

Sorry ... it compiles now and corresponding JS after compilation looks good...  
I had bad spacing in last PR.

Quick Fix on the spacing of the coffeescript file for Lodash 4 compability

---

src/coffee/directives/api/models/parent/circle-parent-model.coffee

Add "coordinates" reference checking and object reference checking of "geoJSON" to $watchCollection for "ui-gmap-circle" directive
https://github.com/angular-ui/angular-google-maps/issues/1679

Improvе "center" watcher  "ui-gmap-circle" directive for "geoJSON" compatibility

---

example/assets/scripts/controllers/search-box-autocomplete.js
example/assets/scripts/controllers/search-box-ngmodel.js
example/assets/scripts/controllers/search-box.js
example/search-box-autocomplete.html
example/search-box-ngmodel.html
example/search-box.html

- updated angular 1.3.8 to 1.5
- fixed error where marker clicks failed to open windows

fix(examples): searchbox

---

app/views/examples/map-control/index.html
app/views/examples/map-control/script.js
bower.json

Documentation update for PR #1801

Inline template in map-control directive - Documentation

---

example/assets/scripts/controllers/many-polygons.js
example/issue-930-polygons-updates.html
example/many-polygons.html

Trying to wrap my head around Polygons and sadly many examples are incomplete.
Also the Polygons example on the website is missing: http://angular-ui.github.io/angular-google-maps/#!/api/polygons

Restore functionality of clickable Polygons examples

---

app/views/examples/base/plnkr.html

Fix for issue #1910. 
I added the dependency to `angular-simple-logger`.

Update base plnkr.html file

---

dist/angular-google-maps.js
spec/coffee/directives/api/models/parent/map-types-parent-model.spec.coffee
src/coffee/directives/api/models/parent/map-type-parent-model.coffee
src/coffee/directives/api/models/parent/map-types-parent-model.coffee
src/coffee/directives/map-types.coffee

Proposed enhancement for maintaining order of many map-type layers.
[This fiddle](http://jsfiddle.net/eczajk1/kqa68ue1/) shows the new directive in action, compared to the fiddle shown in #1871.
I realize that this is a fairly heavy PR and people are busy, so thanks in advance for any feedback that anyone can offer.

Map types directive

---

src/coffee/directives/api/map.coffee

Before the fix it was only updating if the event was disabled. #1865

Fix updateCenter() so it correctly updates center values #1865

---

app/views/examples/drawing-manager/script.js

The Plnkr example now works correctly. I had to add a dependency to the `drawing` library and wait for the `uiGmapGoogleMapApi.then` promise to resolve before drawing anything.

[drawing manager example script] Fixes

---

views/provider/GoogleMapApi.html

The existing link points to lines of code that are not the default params.
This PR includes an update to the existing link.

Fixed default params link to the lines of code
