angular-ui/angular-google-maps

example/assets/scripts/controllers/issue-1075-markers-icon-change.js
example/issue-1075-markers-icon-change.html
src/coffee/directives/api/models/child/marker-child-model.coffee

I was getting this error when using the new plural code:
```
TypeError: Cannot read property 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png' of undefined
at MarkerChildModel.angular.module.factory.ModelKey.scopeOrModelVal (http://localhost:3100/dist/angular-google-maps_dev_mapped.js:1396:60)
at MarkerChildModel.angular.module.factory.ModelKey.getProp (http://localhost:3100/dist/angular-google-maps_dev_mapped.js:1328:23)
at MarkerChildModel.__bind [as getProp] (http://localhost:3100/dist/angular-google-maps_dev_mapped.js:1265:63)
at http://localhost:3100/dist/angular-google-maps_dev_mapped.js:3164:32
at MarkerChildModel.angular.module.factory.MarkerChildModel.renderGMarker (http://localhost:3100/dist/angular-google-maps_dev_mapped.js:3040:15)
at …
```

1075 - patch for getting the icon model property

---

curl.json

MarkerWithLabel 1.1.10: Fix for forgetting to clean up invisible click nodes when changing label content.
source: 
http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.10/src/markerwithlabel.js
source diff : 
https://code.google.com/p/google-maps-utility-library-v3/source/diff?spec=svn473&r=468&format=side&path=/trunk/markerwithlabel/src/markerwithlabel.js&old_path=/trunk/markerwithlabel/src/markerwithlabel.js&old=464

Update curl.json - for latest markerwithlabel.js source

---

curl.json

latest version of infobox (1.1.13) which fixes this iOS issue :
http://stackoverflow.com/questions/9229535/google-maps-markers-disappear-at-certain-zoom-level-only-on-iphone-ipad
source diff:
https://code.google.com/p/google-maps-utility-library-v3/source/diff?spec=svn466&r=466&format=side&path=/trunk/infobox/src/infobox.js

Update curl.json - for latest infobox.js source

---

src/coffee/directives/api/managers/clusterer-marker-manager.coffee
src/coffee/directives/api/models/parent/rectangle-parent-model.coffee

Fixes as I understand it should be.
The `opt_internal_events` identifier is used only once, so IMHO that line can be removed.

Fixing some undefined variables bugs #1161 and #1162

---

package.json

It should not be done in post-install because these actions should only be done in development.

Remove post-install script

---

.gitignore
README.markdown
package.js

Hi @nmccready
I'm a package maintainer for Meteor.js, a popular [full-stack JavaScript framework](https://www.meteor.com/).
I'm also the creator of [angular-meteor](http://angularjs.meteor.com/), a library that let's you work with AngularJS on top of Meteor.
A lot of our users use angular-google-maps and right now there is a separate package and Github repo that simply manually copies your distribution and publish it to Meteor.
There is also a [tutorial about working with Meteor, AngularJS and angular-google-maps](http://angularjs.meteor.com/tutorial-02/step_16).
This PR is a start to allow you to directly publish updated versions of angular-google-maps to Meteor as they become available. 
All you have to do is create an account at https://meteor.com/ (click SIGN IN, then Create account). …

(chore): Add packaging for Meteor.js

---

src/coffee/directives/api/utils/model-key.coffee

I don't think commit 3586ca2 fixes #564 as show http://plnkr.co/edit/rgAg2rwcsPrU0RxWeNLS?p=preview
This fix allows nested coords properties for marker models.

Fix for https://github.com/angular-ui/angular-google-maps/issues/564

---

example/assets/scripts/controllers/markers-models-objects.js

'Uncaught TypeError: undefined is not a function' when attempting to load markers-models-objects example.

typo in call to uiGmapObjectIterators.slapAll

---

src/coffee/directives/api/models/child/marker-child-model.coffee

When the marker has a label without "labelAnchor" specified and the position changes, "labelAnchor" is reset from the default (a Point at 0,0) to undefined. This is because the default is set only when the marker label is created. As a result of this, MarkerLabel.setAnchor throws an error trying to access the "x" property on the undefined anchor.
This PR will prevent the default from being overwritten and these exceptions from being thrown (which also causes the map to lock up).

fix(markerLabel): don't reset the anchor on change

---

src/coffee/directives/api/models/child/marker-child-model.coffee
src/coffee/directives/api/models/child/window-child-model.coffee

solves issue #1350
See https://github.com/angular-ui/angular-google-maps/issues/1350
for a discussion on lodash dependency and ways to get rid of it.

replaced _.extend calls by _.clone calls

---

app/views/provider/GoogleMapApi.html
app/views/service/IsReady.html

Attempting to resolve #1343. Seems like a minor change, but feedback definitely welcome.

GoogleMapApi and IsReady descriptions are explicit about usage re control object augmentation

---

app/views/directive/google-map.html

Missing `control='{Object}'` in the signature.

Add missing control attribute

---

app/views/directive/google-map.html
app/views/directive/markers.html
app/views/directive/partials/polys.html
app/views/directive/polygon.html
app/views/directive/windows.html
app/views/provider/GoogleMapApi.html
app/views/service/Async.html
app/views/service/IsReady.html
app/views/service/Logger.html
app/views/service/Promise.html
app/views/service/PropMap.html

The links to source code were broken since they referenced `develop` branch which is not around anymore.
I also took the time to update the directives parameters section so now the required properties are first.

updated links to source code and ordered parameters - mandatory first

---

src/coffee/directives/api/utils/model-key.coffee

Attempting to resolve #1385 by using `_.get` in `ModelKey.scopeOrModelVal`.
Verified to work against [MCVE at #1385](http://plnkr.co/edit/8mqemGQ3jJsJGd32sPfS?p=preview), and our main example template seems to run with all functionality and with no console errors.
Unless `_.get` is already used elsewhere in the source, this introduces a dependency on [lodash 3.7.0+](https://github.com/lodash/lodash/wiki/Changelog#v370).

Allow path-like strings to specify nested properties

---

src/coffee/directives/api/utils/is-ready.coffee

Replaces PR #1382
Resolves _currentCheckNum never being reset, causing 'Your maps are not found we have checked the maximum amount of times. :)' error after several destroying and recreating of map controls (http://plnkr.co/edit/N7xB5T).
Adds number of retries has a failsafe timeout value, defaulting to 50 and replacing _maxCtrChecks.

Adds numRetries parameter to uiGmapIsReady.promise()

---

app/views/directive/marker.html

As the Issue #1408, the documentation should be explain how to use icon for single ui-gmap-marker which suppose to be inside the options attribute/object.

Fix Issue #1408 Custom Icon which works inside options for single ui-gmap-marker

---

.travis.yml
bower.json
circle.yml
grunt/jasmine.coffee
grunt/options.coffee
package.json

running `grunt jasmine:underscoreSpec` proves that underscore works as
well
issue #1509

feat(underscore):support specs against underscore

---

package.js

The node version requires a minimum of 3.8, lets let the meteor version use the latest lodash as well. This will fix problem in my project where I can't use lodash version newer than 1 if I include this package.

upgrade to using latest lodash

---

example/issue_1542_cartodb.html
src/coffee/directives/api/models/parent/map-type-parent-model.coffee

Proposed solution to item that was piggy-backed onto issue #1542 .
Idea is to check equality on specific properties of options object -
then trigger the map refresh.
So if your maptype (e.g. cartodb layer) relies on additional
properties/functions that are subject to change - but do not require a
map refresh, you won't get the flickering effect.

check maptype properties before refresh

---

src/coffee/providers/map-loader.coffee

This fixes an error raised when a script tag for Gmaps API is already in the document.
See issue https://github.com/angular-ui/angular-google-maps/issues/1521

Replace remove() with removeChild() to delete an existing script tag

---

app/views/examples/windows/script.js

Toggling an InfoWindow didn't work because $scope.onClick receives the marker object, not the model as the first argument.
After this change one can toggle an InfoWindow by clicking on a marker, but there is still a problem somewhere, because it stops working if I change the 'show' key to anything else: http://plnkr.co/edit/Je2yTpbBZ1aEEpga8les?p=preview

Use correct markers.click arguments

---

src/coffee/utils/array-sync.coffee

Two guard clauses have been combined into one. Previously one clause
was checking for the object's existence, the other was checking for
its attributes. Now the same guard clause chains the conditions
together thereby reducing a code line.

combined 2 guard clauses

---

app/views/directive/marker-label.html

While browsing the API, I found that the links on the `marker-label` page to `marker` and `markers` weren't working.
I have added the `ui-sref`-attribute, corrected the `href`-attribute and added the `ng-binding`-class so they are consistent with the links I found on the `markers` page.

Repaired broken links

---

src/coffee/directives/api/map.coffee
src/coffee/directives/api/utils/gmap-util.coffee

Removed the requirement for `bounds`, `center` and `zoom` attributes on the `ui-gmap-google-map` directive. Now only a `center` or `bounds` attribute is required, and the `zoom` attribute is optional (it defaults to 10). If only the `bounds` attribute is specified, the `center` lat/long is derived. Closes #1360.

Fixed bounds, center and zoom handling

---

bower.json

Added license in order to prevent WebJar to fail when attempting to find license on bower.json

Added license

---

package.json

fixes failure of grunt-webpack: Cannot find module 'webpack-dev-server' when running grunt in project

fix(build): webpack-dev-server is a peer dependency of grunt-webpack

---

example/issue_1466_map_flicker.html
example/issue_1542_cartodb.html
example/issue_1574_marker_dupes.html

`lodash.min.js` no longer exists in the root lodash folder resolved by bower which was breaking any examples that referenced this file. This fix replaces these with the unminified version, as this is guaranteed to exist and keeps things consistent with the other (unminified) dependencies.
Happy to change this to use the file in `dist/lodash.min.js` if it's required, or switch to cloudflare like some of the other examples do.
Cheers

Fix incorrect lodash paths in examples

---

src/coffee/directives/api/models/parent/base-polys-parent-model.coffee

I believe that the call to setChildScope in BasePolysParentModel.createChild was omitting to pass the IPoly.scopeKeys argument, as the earlier call a few lines earlier does pass it. This was causing the following exception at runtime:
TypeError: Cannot convert object to primitive value
at RegExp.test (native)
at isKey (...)
at baseGet (...)
at Function.get (...)
at BasePolysParentModel._Class.scopeOrModelVal (...)
at BasePolysParentModel._Class.setChildScope (...)
at BasePolysParentModel.setChildScope (...)
at ...
at Scope.$digest (...)
at ...(anonymous function) @ angular.js:13642(anonymous function) @ angular.js:10287$digest @ angular.js:17238(anonymous function) @ angular.js:17417completeOutstandingRequest @ angular.js:5912(anonymous function) @ angular.js:6191

Fix missing first argument in call to setChildScope in BasePolysParentModel

---

example/assets/scripts/controllers/issue-1485-doRebuildAll.js
example/issue-1485-doRebuildAll.html
spec/coffee/directives/api/utils/model-key.spec.coffee
src/coffee/directives/api/markers.coffee
src/coffee/directives/api/models/parent/markers-parent-model.coffee
src/coffee/directives/api/plural.coffee
src/coffee/directives/api/utils/model-key.coffee

fix(model-key): model-key comparison on objects  
Change model-key to use lodash to compare objects
- When objects (outside of coords) are compared via ===, the comparison always returns falls, even if objects are same.  Thus, with a false comparison, all markers get marked as needing update, negating doRebuildAll=false.  This fixes false negative on comparison.
- Add simple examples page with examples controller for issue #1485.
- Update model-key spec to include a non-coord comparison on models
Closes #1485

Fix Issue #1485 - Model-Key comparison

---

spec/coffee/directives/api/control.spec.coffee
src/coffee/directives/api/control.coffee

Transclude function was called multiple times causing that the transcluded content to get attached to page multiple times

Fixed error in map control

---

src/coffee/directives/api/control.coffee
src/coffee/directives/search-box.coffee

This PR fixes [#1989](https://github.com/angular-ui/angular-google-maps/issues/1989).
The `.success` and `.error` methods are deprecated and have been removed from [AngularJS 1.6](https://github.com/angular/angular.js/commit/b54a39e2029005e0572fbd2ac0e8f6a4e5d69014). Use the standard `.then` and `.catch` method instead.
Before:
```js
$http(...).
success(function onSuccess(data, status, headers, config) {
// Handle success
...
}).
error(function onError(data, status, headers, config) {
// Handle error
...
});
```
After:
```js
$http(...).
then(function onSuccess(response) {
// Handle success
var data = response.data;
var status = response.status;
var statusText = response.statusText;
var headers = response.headers;
var config = response.config;
...
}, function onError(response) {
// Handle …
```

$http's deprecated custom callback methods
